### ISSUE TITLE
第五话《We Have A Dream》歌分错误

### ISSUE THREAD

**Issue by fireattack** [Kitauji-Sub/subs-imas-million#1]
粗体为字幕错误，修正后的正确演唱者

楽しいこと　やりたいこと　数え切れないほど　**未来**
毎日忙しすぎても夢は忘れないわ　静香
どうでもいいことに心すり減らして　翼
行き先見失うの　それだけは避けたい　（ALL）

少しくらい遠回りで人より遅れても　百合子
道草も楽しめるから負けた気はしないわ　星梨花
立ち止まる時でも歩みは止めないの　**杏奈**
いつでも動き出せる準備怠らない　まつり

...

仕事が第一　百合子
恋は禁止　**星梨花**
分かってるつもり　**杏奈+まつり**

...
人数多いけど
それぞれがとても　静香
個性的で　翼
退屈しないよ　未来

**Comment by scrpr** [comment]
感谢捉虫，已修复于 4e13cd6
